### ISSUE TITLE
Can we add a `cloud_meta()` function to return header info?

### ISSUE THREAD

**Issue by tarensanders** [pdparker/cloudstoR#1]
As in, to return information about the file, without having to download the actual file. 

Looking at the XML returned from the `cloud_list` function, it looks like `d:getlastmodified`, `d:quote-used-bytes`, `d:getcontentlength`, etc are present. These could be passed to [targets](https://github.com/ropensci/targets) as a way to check for file changes.

**Comment by pdparker** [comment]
Yep I think this is a good idea. I suppose we could return a tibble or similar with all the info

**Comment by pdparker** [comment]
@tarensanders can you review?

**Comment by tarensanders** [comment]
@pdparker this is great! The only issue I've found is that I think size should come from 'getcontentlength' rather than 'quota-used-bytes', as the latter only seems to apply to folders. The contentlength seems to be file size in bytes (e.g., the 795.5MB csv file for belonging returns 834143890. 834143890/1024/1024 = 795.5016).

This is also an issue because putting a single file in as the cloud address results in an error (because file_size is NULL, so different length from the others).

I'll make this change.

**Comment by tarensanders** [comment]
Just a note that I changed this to use contentlength by default, but fall back to get-used-quota if there is no content length.
