### ISSUE TITLE
Add method to store credentials

### ISSUE THREAD

**Issue by tarensanders** [pdparker/cloudstoR#2]
Passing credentials into the function means that they end up in the history file, and are likely to end up getting committed to repos. A better option would be to store the credentials in a method that bypasses those issues, but still leaves them available  if a user wants to quickly run the function.

I'm proposing that we use [keychain](https://cran.r-project.org/web/packages/keyring/keyring.pdf) to store the credentials. It's not the most secure, but it's better than plain text. I'm suggesting it works like this:
* the `cloud_*` functions have as defaults `user = cloud_auth_user()` and `pass = cloud_auth_password()`. These check if a key exists, and if not calls `cloud_auth()`.
* `cloud_auth()` asks the user to provide the key and stores it using keychain
* At anytime you can ignore this, just by directly passing a username or password.

I've opened a branch (cloud_auth) with the functions to do this. Once it's finished I'll open a PR for you to check.

**Comment by pdparker** [comment]
LGTM
