### ISSUE TITLE
cloud_* functions getting 401 error

### ISSUE THREAD

**Issue by ChrisBollands** [pdparker/cloudstoR#23]
Trying to access cloudstor using cloudstoR on Rstudio.
Installing works fine but when running any cloud_* function, for example
```
my_data <- cloud_get(path = 'test/test.csv', username = '***', password = '***')
```
I am getting the error 
```
Error in curl::curl_download(cloud_address, p, handle = h) : 
  The requested URL returned error: 401
```

I have created an app password which I am using.

Thanks in advance!

**Comment by tarensanders** [comment]
Hi @ChrisBollands,

A 401 error is almost always means a problem with credentials. Just to check the obvious, your credentials should look something like:

Username: name@xyz.edu.au
Password: ABCDE-FGHIJ-KLMNO-PQRST

The app passwords are always 20 uppercase letters separated by dashes - does yours look like that?

**Comment by ChrisBollands** [comment]
Hi @tarensanders 
It seems to be working now, I have no idea why, the picture below is me using the same command 5 minutes apart and the bottom imports the correct csv despite the warning. I have checked the commands and they are identical! It all seems to be working now, thanks for the quick response nonetheless

![Screen Shot 2022-08-01 at 12 49 32 pm](https://user-images.githubusercontent.com/13778200/182069480-c57adb20-834f-417a-bb9a-446ae1a24663.png)

**Comment by tarensanders** [comment]
Glad it's working, @ChrisBollands. Do you get the warning every time you try to read a CSV?

Full disclosure - I've never used the `username = ..., password = ...` outside of tests because we set cloudstoR up to securely store credentials in your keychain, so there could be weird little bugs in that system that I haven't seen. If you get it every time let me know and I'll see if I can replicate it.

**Comment by tarensanders** [comment]
Ahh, nevermind. I just realised that it should be `user = ...` not `username = ...`.

Sorry, I can see that this is wrong in the docs. I will fix it now.

**Comment by ChrisBollands** [comment]
user =  works perfectly and I no longer get the warning, thanks a lot!
