### ISSUE TITLE
Seperate webdav address and subfolder/file location into seperate arguments.

### ISSUE THREAD

**Issue by pdparker** [pdparker/cloudstoR#5]
Would be worth splitting the global webdev address (so this can be set globally) from file/folder navigation in all functions.

**Comment by tarensanders** [comment]
Can I add to this that the file/folder should be the first argument to all the functions.

I keep doing `cloud_*(<path_to_file>)` which fails because it has to be `cloud_*(cloud_address=<path_to_file>)`. Seems like this is the most common use of all the functions.

**Comment by pdparker** [comment]
Yes this makes sense to me
